version: '3.8'
services:
  app:
    container_name: db
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres          
    networks:
      - db


  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=root  
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_banks_tanzania
      - DATABASE_HOST=root 
    ports:
      - '5424:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - db
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "gfrankgef@gmail.com "
      PGADMIN_DEFAULT_PASSWORD: 12349
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - db
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge